name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: stable
            override: true
      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: clippy
        with:
          command: clippy
          args: -- -D warnings
